language: node_js
before_script:
  - npm install -g gatsby
node_js:
  - "10"
script:
  - gatsby build
deploy:
  provider: surge
  skip_cleanup: true
  project: ./public/
  domain: jarstelfox-io.surge.sh
